version: 2
updates:
  # 1. Python dependencies (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 5

  # 2. GitHub Actions (Workflow updates)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # 3. Dockerfile base image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
